b2network/b2-indexer

internal/logic/bitcoin/bridge.go
Closes: #XXX
______
______
For admin use:
=> fix: wait mined status

internal/config/abi.go, internal/config/testdata/abi.json, internal/logic/bitcoin/bridge.go, internal/logic/bitcoin/bridge_deposit_service.go, internal/logic/bitcoin/bridge_test.go, internal/logic/bitcoin/testdata/abi.json, internal/model/deposit.go
Closes: #XXX
______
______
For admin use:
=> status check

internal/logic/bitcoin/bridge.go
Closes: #XXX
______
______
For admin use:
=> fix: btc hash to evm hash

internal/logic/bitcoin/bridge_deposit_service.go, internal/model/deposit.go
Closes: #XXX
______
______
For admin use:
=> fix: word spelling

internal/logic/b2node/b2node.go, internal/logic/b2node/b2node_indexer_service.go, internal/logic/bitcoin/bridge.go, internal/logic/bitcoin/bridge_deposit_b2node_service.go, internal/logic/bitcoin/bridge_deposit_service.go, internal/server/start.go, internal/types/b2node_indexer.go
Closes: #XXX
______
______
For admin use:
=> feat: b2node update deposit

internal/logic/b2node/create_deposit_service.go, internal/logic/b2node/update_deposit_service.go, internal/logic/bitcoin/bridge_deposit_service.go, internal/model/b2node.go, internal/model/b2node_test.go, internal/server/start.go
Closes: #XXX
______
______
For admin use:
=> refactor: change service name

internal/logic/b2node/b2node.go
Closes: #XXX
______
______
For admin use:
=> fix: nonces repeat

internal/logic/bitcoin/indexer.go, internal/logic/bitcoin/indexer_service.go
Closes: #46 
______
______
For admin use:
=> fix: skip empty from

internal/logic/bitcoin/indexer.go, internal/logic/bitcoin/indexer_service.go, internal/logic/bitcoin/indexer_test.go, internal/model/deposit.go, internal/types/bitcoin_indexer.go
Closes: #XXX
______
______
For admin use:
=> feat: add parse field

internal/logic/bitcoin/indexer.go
Closes: #XXX
______
______
For admin use:
=> refactor: modify log level

internal/logic/bitcoin/bridge_withdraw_service.go, internal/logic/rollup/indexer_service.go, internal/logic/rollup/rollup_service.go, internal/logic/rollup/utils.go, internal/model/rollup_index.go, internal/server/start.go
Closes: #XXX
______
______
For admin use:
=> modify bridge withdraw

internal/cmd/cmd.go, internal/config/config.go, internal/logic/bitcoin/bridge.go, internal/logic/bitcoin/bridge_deposit_service.go
Closes: #62 
* fix: set gas price & big int mul
* refactor: timeout & retry
* fix: estimate gas price
* style: format
______
______
For admin use:
=> Fix gasprice (#61)

go.mod, go.sum, internal/cmd/cmd.go, pkg/sinohope/cmd/cmd.go
Closes: #XXX
______
______
For admin use:
=> feat: sinohope cmd

internal/app/service/sinohope.go
#94 
______
______
For admin use:
=> feat: withdraw notify

internal/config/config.go, internal/logic/bitcoin/transfer_service.go
Closes: #XXX
______
______
For admin use:
=> modify transfer

internal/app/exceptions/notify.go, internal/app/service/sinohope.go
#94 
______
______
For admin use:
=> feat: check withdraw params

internal/app/exceptions/notify.go, internal/app/service/sinohope.go
#94 
______
______
For admin use:
=> Mpc node callback

internal/app/service/sinohope.go
#94 
______
______
For admin use:
=> fix: withdraw confirm response set requestid

go.mod, go.sum, internal/app/service/mpc.go, internal/app/service/sinohope.go, internal/cmd/cmd.go, internal/cmd/transfer.go, resource/sql/b2-indexer.sql
#94 
* init reset transfer cmd
* change withdraw query condition
______
______
For admin use:
=> feat: init reset transfer cmd

internal/app/service/sinohope.go
Closes: #XXX
______
______
For admin use:
=> fix: log print detail

internal/app/service/mpc.go
Closes: #XXX
______
______
For admin use:
=> fix: print mpc amount parse err

internal/app/service/mpc.go, pkg/sinohope/types/callback.go
Closes: #XXX
______
______
For admin use:
=> fix: unmarshal tx info

internal/app/service/mpc.go
Closes: #XXX
______
______
For admin use:
=> fix: replace query field

internal/app/service/mpc.go
Closes: #XXX
______
______
For admin use:
=> fix: remove wait status

internal/cmd/transfer.go, internal/model/sinohope.go, internal/model/withdraw_reset_history.go
#94 
______
______
For admin use:
=> feat: reset transfer cmd

internal/app/service/sinohope.go, internal/cmd/transfer.go, internal/logic/bitcoin/transfer_service.go, internal/model/withdraw_reset.go, internal/model/withdraw_reset_test.go
reset transfer cmd
______
______
For admin use:
=> feat: reset transfer

internal/app/service/mpc.go
Closes: #XXX
______
______
For admin use:
=> debug approve

internal/app/service/sinohope.go, internal/cmd/cmd.go, internal/cmd/indexer.go, internal/logic/bitcoin/indexer_service.go
fix: deposit sinohope Lock conflict
feat: add retry indexer deposit cmd
______
______
For admin use:
=> Hotfix v1.1.1 deposit indexer fail

internal/logic/bitcoin/bridge.go, internal/logic/bitcoin/bridge_deposit_service.go, internal/logic/bitcoin/indexer.go, internal/logic/bitcoin/indexer_service.go, internal/model/deposit.go, internal/server/transfer.go, internal/types/bitcoin_indexer.go, resource/sql/b2-indexer.sql
#152
______
______
For admin use:
=> Index op_return

internal/logic/bitcoin/bridge_deposit_service.go, internal/logic/bitcoin/indexer_service.go
#153 
______
______
For admin use:
=> fix: evm address check

internal/cmd/cmd.go, internal/cmd/withdraw.go, internal/logic/bitcoin/bridge_withdraw_service.go, internal/logic/rollup/indexer_service.go, internal/model/withdraw_record.go, resource/sql/b2-indexer.sql
Closes: #XXX
______
______
For admin use:
=> add withdraw one-to-many transactions 

internal/logic/bitcoin/indexer_service.go
Closes: #XXX
______
______
For admin use:
=> Indexer btc

.github/workflows/build-latest.yaml
Closes: #XXX
______
______
For admin use:
=> ci: update build-latest.yaml
